### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Brottweiler** [OvercastCommunity/Issues#1]
TODO
====

#### Make things work standalone
- [ ] Reports (`/report` command sends to staff)
- [ ] Flairs and permissions (WIP) (reads from file)
  - [ ] `/staff` (shows staff with proper permission)
- [ ] Persistent bukkitsettings

#### Versions
- [x] 1.12 (Electroids)
- [ ] 1.13
- [ ] 1.14

#### Other
- [ ] Autorestart (`stop`s then runs `start.sh`?)
- [ ] Toggle arrow trail (https://github.com/applenick/ProjectAres/commit/b9a8266527f211dc84c2eb2656acdbee05e30cf5#r21065480)
- [ ] Disable `/server` and `/servers`
- [ ] Properly fix 2nd skin layer not showing (https://github.com/OvercastNetwork/SportBukkit/issues/241)
- [x] Show current map playing in MoTD
- [ ] Disable premium (So we don't see "Premium users can choose their team)
- [ ] Disable raindrops
- [ ] Fix join messages not showing up?

## Misc

- [x] Some custom logo
